### ISSUE TITLE
大佬，是否能提供其中某个领域的数据集，谢谢！

### ISSUE THREAD

**Issue by essencejay** [HillZhang1999/NaSGEC#5]

**Comment by HillZhang1999** [comment]
您好，我们计划最近基于该数据集组织评测，届时将以榜单形式开源。

**Comment by essencejay** [comment]
老师能否给出几条数据例子，因为我是新手，想先跑通这个项目，然后再深入学习下代码。我想确认的是train/src.txt和train/tgt.txt是不是直接对应放两个中文句子就行，然后就可以去跑了？例如：
src.txt中写一个：依法制国
tgt.txt中写一个：依法治国
给老师添麻烦了，感谢😊对小白的指点



---- 回复的原邮件 ----
| 发件人 | Yue ***@***.***> |
| 日期 | 2023年08月26日 17:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HillZhang1999/NaSGEC] 大佬，是否能提供其中某个领域的数据集，谢谢！ (Issue #5) |

您好，我们计划最近基于该数据集组织评测，届时将以榜单形式开源。

**Comment by HillZhang1999** [comment]
理解的没问题

**Comment by essencejay** [comment]
好勒，感谢大佬指点 @HillZhang1999

**Comment by essencejay** [comment]
好勒，感谢大佬指点 @HillZhang1999
