### ISSUE TITLE
finetune.sh微调时: preprocess.py 报告task无效？

### ISSUE THREAD

**Issue by essencejay** [HillZhang1999/NaSGEC#6]
使用模型:  real_learner_bart_CGEC （脚本已经调整且generate.sh测试成功，但是finetune.sh出现如下错误）
控制台显示:
preprocess.py: error: argument --task: invalid choice: 'syntax-enhanced-translation' (choose from 'translation', 'multilingual_translation', 'translation_lev', 'language_modeling', 'sentence_ranking', 'sentence_prediction', 'cross_lingual_lm', 'multilingual_masked_lm', 'speech_to_text', 'translation_multi_simple_epoch', 'translation_from_pretrained_bart', 'denoising', 'multilingual_denoising', 'masked_lm', 'translation_from_pretrained_xlm', 'semisupervised_translation', 'audio_pretraining', 'legacy_masked_lm', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')

跟踪代码:
preprocess.py：    task = tasks.get_task(args.task)
syntax_guided_gec_task.py:                        @register_task("syntax-enhanced-translation")
                                                                    class SyntaxEnhancedTranslationTask(TranslationTask):

**Comment by HillZhang1999** [comment]
Fixed

**Comment by essencejay** [comment]
> Fixed

okay.i try again
