### ISSUE TITLE
HillZhang/real_learner_bart_CGEC_exam使用demo测试，模型的输出长度不超过20个字，这是什么问题？

### ISSUE THREAD

**Issue by ccdf1137** [HillZhang1999/NaSGEC#9]
输入 ['朋友，请记住，无论你身处何种境地，永远不要自暴自弃，你要相信，自己就是一块璞玉，只要用心雕琢，就会成为一块美玉光芒四射']

输出 ['朋 友 ， 请 记 住 ， 无 论 你 身 处 何 种 境 地 ，']

**Comment by HillZhang1999** [comment]
transformers默认的generation最大长度为20个token，可使用如下代码设置`max_new_tokens`进行控制：
```
output = model.generate(**encoded_input, max_new_tokens=512)
```

**Comment by ccdf1137** [comment]
非常感谢
